<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AssemblyName>HeroHourSimulation.Runner</AssemblyName>
    <RootNamespace>HeroHour.Simulation.Runner</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HeroHourSimulation.fsproj" />
  </ItemGroup>

</Project>
